/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TFB_module */

#ifndef _Included_TFB_module
#define _Included_TFB_module
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TFB_module
 * Method:    updateScreen
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_TFB_module_updateScreen
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
