/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TFB_module_Runner */

#ifndef _Included_TFB_module_Runner
#define _Included_TFB_module_Runner
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
